import {IconName} from '../components/atoms/IconRegistry';

// ─── Icon list (full registry) ────────────────────────────────────────────────
export const CATEGORY_ICONS: IconName[] = [
  // Food & Dining
  'utensils',
  'utensils-crossed',
  'coffee',
  'pizza',
  'sandwich',
  'wine',
  'beer',
  'soup',
  'cooking-pot',
  'apple',
  'cherry',
  'grape',
  'banana',
  'carrot',
  'beef',
  'fish',
  'egg',
  'milk',
  'ice-cream',
  'croissant',
  'salad',
  'cookie',
  'cake',
  'cake-slice',
  'candy',
  'popcorn',
  'wheat',
  'citrus',
  'leafy-green',

  // Transport
  'car',
  'car-front',
  'bus',
  'train',
  'tram-front',
  'plane',
  'plane-takeoff',
  'plane-landing',
  'bike',
  'ship',
  'sailboat',
  'fuel',
  'parking-circle',
  'truck',
  'ambulance',
  'navigation',
  'map-pin',
  'map',
  'compass',
  'route',

  // Shopping
  'shopping-cart',
  'shopping-bag',
  'package',
  'package-open',
  'tag',
  'tags',
  'store',
  'shirt',
  'watch',
  'gem',
  'crown',
  'gift',
  'percent',
  'badge-percent',

  // Finance
  'wallet',
  'landmark',
  'banknote',
  'receipt',
  'piggy-bank',
  'trending-up',
  'trending-down',
  'hand-coins',
  'coins',
  'circle-dollar-sign',
  'credit-card',
  'calculator',
  'arrow-up-circle',
  'arrow-down-circle',

  // Home & Utilities
  'house',
  'building',
  'building-2',
  'lightbulb',
  'zap',
  'droplet',
  'droplets',
  'flame',
  'wind',
  'wifi',
  'phone',
  'smartphone',
  'tv',
  'monitor',
  'laptop',
  'gamepad-2',
  'plug',
  'cable',
  'thermometer',
  'air-vent',
  'bath',
  'bed-double',
  'sofa',
  'lamp',
  'door-open',
  'key',
  'lock',
  'shield-check',
  'shield',

  // Health & Wellness
  'heart',
  'heart-pulse',
  'activity',
  'pill',
  'stethoscope',
  'syringe',
  'bandaid',
  'hospital',
  'cross',
  'brain',
  'dumbbell',
  'person-standing',
  'footprints',
  'glasses',
  'smile',
  'moon',
  'sun',
  'umbrella',

  // Entertainment
  'music',
  'music-2',
  'headphones',
  'film',
  'clapperboard',
  'camera',
  'image',
  'palette',
  'brush',
  'scissors',
  'sparkles',
  'party-popper',
  'drama',
  'ticket',
  'dice-5',
  'puzzle',
  'blocks',
  'radio',
  'mic',

  // Education & Work
  'book',
  'book-open',
  'book-marked',
  'notebook',
  'notebook-pen',
  'graduation-cap',
  'school',
  'file-text',
  'briefcase',
  'badge-check',
  'award',
  'trophy',
  'medal',
  'target',
  'pen-tool',
  'ruler',
  'presentation',
  'newspaper',

  // Pets & Animals
  'paw-print',
  'cat',
  'dog',
  'bird',
  'bug',
  'fish',
  'rabbit',
  'squirrel',
  'snail',
  'turtle',

  // Nature & Outdoors
  'trees',
  'tree-deciduous',
  'tree-pine',
  'flower',
  'flower-2',
  'sprout',
  'clover',
  'leaf',
  'mountain',
  'mountain-snow',
  'waves',
  'tent',
  'campfire',
  'flashlight',
  'backpack',
  'luggage',
  'globe',
  'earth',
  'sunrise',
  'sunset',
  'cloud',
  'snowflake',
  'star',
  'sparkle',

  // Communication
  'message-circle',
  'message-square',
  'mail',
  'send',
  'bell',
  'bell-ring',
  'megaphone',

  // People & Social
  'users',
  'user',
  'baby',
  'handshake',
  'heart-handshake',
  'thumbs-up',

  // Tech
  'code',
  'terminal',
  'database',
  'server',
  'cpu',
  'printer',
  'qr-code',

  // Miscellaneous
  'clock',
  'timer',
  'hourglass',
  'alarm',
  'repeat',
  'circle-dot',
  'circle',
  'shapes',
  'flag',
  'bookmark',
  'pin',
  'paperclip',
  'link',
  'anchor',
  'wrench',
  'hammer',
  'paintbrush',
  'box',
  'archive',
  'inbox',
  'settings',
  'cog',
  'help-circle',
  'info',
  'alert-circle',
  'verified',
];

// ─── Color palette for category pickers ──────────────────────────────────────
export const CATEGORY_COLORS: string[] = [
  '#3525cd', '#4f46e5', '#FF6B6B', '#6BCB77', '#FFC300',
  '#C77DFF', '#FF9F1C', '#00B4D8', '#10B981', '#EC4899',
  '#8B5CF6', '#F43F5E', '#14B8A6', '#F59E0B',
];

// ─── Default category suggestions shown on Add screen ────────────────────────
export interface DefaultCategorySuggestion {
  name: string;
  icon: string;
  color: string;
}

export const DEFAULT_CATEGORY_SUGGESTIONS: DefaultCategorySuggestion[] = [
  { name: 'Groceries',     icon: 'shopping-cart', color: '#4f46e5' },
  { name: 'Dining Out',    icon: 'utensils',      color: '#FF6B6B' },
  { name: 'Transport',     icon: 'car',           color: '#6BCB77' },
  { name: 'Utilities',     icon: 'zap',           color: '#FFC300' },
  { name: 'Entertainment', icon: 'film',          color: '#C77DFF' },
  { name: 'Health',        icon: 'heart-pulse',   color: '#FF9F1C' },
];
